### ISSUE TITLE
Получение экземпляра(ов) определенного класса с заданным значением свойства

### ISSUE THREAD

**Issue by v--victoria** [tsouvarev/semantic_objects#22]
Получение экземпляра(ов) определенного класса с заданным значением свойства
Аналог ClassName.objects.filter(PropertyName=PropertValue)

При этом хотелось бы иметь возможность задать PropertValue=null, что означало бы: получить экземпляр(ы) класса, для которого(ых) не существует rdf-тройки "экземпляр - свойство - значение свойства".

Необходимо для реализации https://github.com/v--victoria/SemanticWebService/issues/1

**Comment by tsouvarev** [comment]
думаю, так будет лучше: ClassName.objects.filter(PropertyName__isnull=True)
https://docs.djangoproject.com/en/dev/ref/models/querysets/#isnull
заодно можно будет разом прицепить остальные lookups

**Comment by v--victoria** [comment]
ok
