### ISSUE TITLE
Получение значения свойства экземпляра класса по имени свойства

### ISSUE THREAD

**Issue by v--victoria** [tsouvarev/semantic_objects#25]
Имея экземпляр (например, полученный с помощью t = ClassName.objects.get(PropertyName=PropertyValue), хочется получить значение произвольного свойства по строковому имени свойства, как-нибудь так: t.getPropertyValue(propertyName).

**Comment by v--victoria** [comment]
Честно говоря, пока не совсем представляю, где это точно понадобится, и, возможно, достаточно будет записи вида t.PropertyName (т.е. прямое обращение к свойству экземпляра класса). Ваня, что думаешь?

**Comment by tsouvarev** [comment]
сейчас мне это представляется следующим образом: сразу получить список всех доступных свойств (у которых домен совпадает с текущим классом), его объявить через слоты или дескрипторы - пока неясно, что лучше - а дальше при первом обращении получать значение свойства. 
тут есть плюсы - питон контролирует обращение к свойствам, которых нет; свойства находятся сами через MRO, много всего приятного. минусы - для создания свойства у ресурса придется извращаться, но я так понимаю, что изменение схемы сейчас все-таки на втором плане.
